{
    "prefix": "GT",
    "domain": "Service",
    "keys": [],
    "errors": [
        {
            "name": "AccountExistsError",
            "code": 1,
            "description": "Service Account already exists",
            "failure_reason": "A service account with these credentials already exists"
        },
        {
            "name": "AuthenticationError",
            "description": "Bad credentials",
            "failure_reason": "The entered credentials are invalid"
        },
        {
            "name": "GenericAPIError",
            "description": "An API Error Occurred",
            "failure_reason": "API Endpoint responded with an error"
        },
        {
            "name": "PublicKeyAPIError",
            "description": "An API Error Occurred",
            "failure_reason": "API Endpoint responded with an error"
        },
        {
            "name": "AccountPrivilegesError",
            "description": "You need admin privileges to access this action",
            "failure_reason": "API Endpoint responded with an error"
        },
        {
            "name": "AccountQuotaError",
            "description": "You are over your quota",
            "failure_reason": "API Endpoint responded with an error"
        },
        {
            "name": "BeanstalkHostnameLacksAccountNameSubdomainError",
            "description": "Beanstalk URL must contain account name",
            "failure_reason": "Beanstalk URLs are expected to contain the account name as subdomain"
        },
        {
            "name": "MaxLoginAttemptsExceededError",
            "description": "Maximum number of login attempts exceeded",
            "failure_reason": "Try again later"
        },
        {
            "name": "AuthenticationMethodError",
            "description": "2FA is enabled for this Account",
            "failure_reason": "Use 2FA or personal access tokens for authentication"
       },
       {
           "name": "TwoFactorAuthenticationError",
           "description": "Bad OTP Code",
           "failure_reason": "The entered 2FA code is invalid"
       },
       {
           "name": "AccessTokenScopeError",
           "description": "Can not accomplish API call",
           "failure_reason": "Access token rights might not be sufficient"
       }
    ]
}
